# Generated by Django 5.1.7 on 2025-03-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=70, verbose_name='Название новости')),
                ('b', models.CharField(max_length=70, verbose_name='Описание новости')),
                ('c', models.TextField(verbose_name='Новость')),
                ('d', models.DateTimeField(verbose_name='Дата публикации')),
                ('e', models.CharField(max_length=30, verbose_name='Автор')),
            ],
        ),
    ]
